### ISSUE TITLE
'GUID' en 'guid' gelijktrekken

### ISSUE THREAD

**Issue by companje** [hetutrechtsarchief/MDWS-to-JSON#4]
Schrijfwijze verschilt regelmatig.
Wellicht 'GUID' altijd met hoofdletters opnemen in JSON.

```json
    "GUID": "398E0C9327B44CA99C849A26787FB662"
```
```json
    "guid": "7DB682F716664652A2647F988CF7E1DB",
```

**Comment by companje** [comment]
```js
function updateItem(key,val) {
    var value = val.trim();
    if (key=="guid") key="GUID"; //always write GUID in uppercase
 ....
```

**Comment by coret** [comment]
Hoe kan het dat het soms guid en soms GUID is? Door definitie door instelling van inventaris?
Wellicht .toUpperCase() voor alle key's toepassing in vervolg?

**Comment by companje** [comment]
Het komt omdat uitvoerdefinities met de hand worden getypt. Degene die het veld toevoegt verzint zelf hoe die gaat heten.
